### ISSUE TITLE
Scroll to start causes image comparison to fail in Firefox OSX

### ISSUE THREAD

**Issue by meleyal** [zinserjan/wdio-screenshot#11]
[These lines](https://github.com/zinserjan/wdio-screenshot/blob/master/src/modules/beforeScreenshot.js#L11-L18) seem to cause Firefox on OSX to display scroll bars for a short time, which can cause image diffs (via wdio-visual-regression-service) to fail.

**Comment by zinserjan** [comment]
Sorry for the delay.

I can't reproduce this problem on firefox, but I have this issue sometimes with IE 9 . 

Have you the same problem with webdrivercss? If webdrivercss works, we have to find the difference...
The only real difference i found so far is a different order of statements to hide scrollbars and scroll.

Can you test a a version with a different order of statements? Just make a dirty hack and replace `lib/modules/beforeScreenshot.js` in your node_Modules with the file of this [gist](https://gist.github.com/zinserjan/8dac13f163245db1ee8882000bc685e5) and run your tests again.
