### ISSUE TITLE
write EPIPE error when trying to save screenshot

### ISSUE THREAD

**Issue by hristokkanchev** [zinserjan/wdio-screenshot#12]
Hello there!

I get an error message when trying to save a screenshot. This is the error message:

`write EPIPE`
`running firefox`
`Error: write EPIPE`
    `at Object.Future.wait (D:\QA\testscreenshot\node_modules\wdio-mocha-framework\node_modules\wdio-sync\node_modules\fibers\future.js:449:15)`
    `at Object.saveDocumentScreenshot (D:\QA\testscreenshot\node_modules\wdio-mocha-framework\node_modules\wdio-sync\build\index.js:345:27)`
    `at Context.<anonymous> (D:\QA\testscreenshot\test\specs\test.js:6:17)`
    `at D:\QA\testscreenshot\node_modules\wdio-mocha-framework\node_modules\wdio-sync\build\index.js:649:20`
   ` - - - - -`
    `at exports._errnoException (util.js:870:11)`
    `at Socket._writeGeneric (net.js:681:26)`
    `at Socket._write (net.js:700:8)`
    `at doWrite (_stream_writable.js:300:12)`
   ` at writeOrBuffer (_stream_writable.js:286:5)`
    `at Socket.Writable.write (_stream_writable.js:214:11)`
    `at Socket.write (net.js:626:40)`
    `at gm._spawn (D:\QA\testscreenshot\node_modules\wdio-screenshot\node_modules\gm\lib\command.js:249:18)`
    `at D:\QA\testscreenshot\node_modules\wdio-screenshot\node_modules\gm\lib\command.js:140:19`
    `at series (D:\QA\testscreenshot\node_modules\wdio-screenshot\node_modules\gm\node_modules\array-series\index.js:11:36)`

I am running on Windows 10 and all of the required software is installed and wdio is properly configured.

Thanks for the help in advance!

**Comment by zinserjan** [comment]
Have never seen this error before. Can you provide a failing repo?

**Comment by hristokkanchev** [comment]
Sorry for the late reply.

After restarting my computer it was all fixed.

Sorry for the hassle! Thank you for this amazing project!
