### ISSUE TITLE
Mostly blank screen with wdio 4.x and firefox

### ISSUE THREAD

**Issue by bennett000** [zinserjan/wdio-screenshot#20]
I can reproduce this issue and provide code samples if you need.  I've been able to fix this issue by modding my runtime copy of wdio-screenshot.  

## Summary

The short version is that part of my page isn't being captured by the screenshot system and the problem can be fixed by skipping the cropping code that occurs here: https://github.com/zinserjan/wdio-screenshot/blob/master/src/modules/makeAreaScreenshot.js#L46

## Details

- I'm using an Ionic starter project (the tabs one)
- I'm using wdio-visual-regression-service which is handling all the wdio-screenshot calls for me
- I can validate that text exists on the page by testing for it _before_ running the `browser.checkViewport` command
- The reference screenshots only show the tab header
- Inserting pauses has no effect
- Tweaking the `viewportChangeDelay` has no effect
- Calling the wdio-screenshot commands manually also excludes the body
- Calling the wdio screenshot system produces the expected output

## Temporary hack/soltuion

Editing my `node_modules/wdio-screenshot/lib/modules/makeAreaScreenshot.js` to skip the cropping step works as expected

I haven't had the time yet to actually read your code so I don't know what's going on.  I will take a look later this week-end and find the details.  I wondered if you might have any ideas off the top of your head.

**Comment by zinserjan** [comment]
> The short version is that part of my page isn't being captured by the screenshot system and the problem can be fixed by skipping the cropping code that occurs here: 

> running the browser.checkViewport command

browser.checkViewport takes a screenshot of the visible area of your browser. 

If you want to capture full page screenshots  use browser.checkDocument instead.

**Comment by bennett000** [comment]
@zinserjan thanks for the ultra-fast reply!

I should have mentioned that I tried `checkDocument` as well as specifically trying `checkElement` and both end up blank.  The element is a smaller image, but just blank.

I'm wondering if this particular Ionic app produces an edge case that causes crop to return blank.

**Comment by zinserjan** [comment]
Ah ok. Do you get the same result with chrome or is this just a firefox issue?

Can you provide me an sample repo with instructions how to run it?

**Comment by bennett000** [comment]
@zinserjan I haven't tried Chrome yet, I was in a bit of a rush.  I did setup a demo repo though:

## Installation 
- `npm install -g ionic` or add it after to avoid the global 
- `git clone https://github.com/bennett000/webdriver-test.git`
- `git fetch`
- `git checkout feat-visual-regression`
- `cd ./webdriver-test/myApp`
- `npm install`

## Running the test 

- `ionic serve` (from the myApp folder) or `./node_modules/.bin/ionic serve` if you installed locally
- start selenium (2.53.1 is the version I'm using)
- `npm run test`

Ionic is basically just Cordova + Angular + Sugar

**Comment by zinserjan** [comment]
The scrolling code seems to be the issue. Btw same issue with Chrome.

You can reproduce this when you paste the following code in your browser's console:

```javascript
function virtualScroll(x, y, remove = false) {
  const w = x === 0 ? 0 : -1 * x;
  const h = y === 0 ? 0 : -1 * y;

  const translate = remove ? 'none' : `translate(${w}px,${h}px)`;
  const html = document.documentElement;

  html.style.webkitTransform = translate;
  html.style.mozTransform = translate;
  html.style.msTransform = translate;
  html.style.oTransform = translate;
  html.style.transform = translate;
}
virtualScroll(0,0)
```

**Comment by bennett000** [comment]
Sorry what's the context on the scrolling code?  I don't think I've seen that function before.

**Comment by zinserjan** [comment]
That's the code which is internally used by webdrivercss and this project to position the page into the viewport. This is necessary cause most browsers can only take screenshots of the viewport. That's why we have to scroll the page, take a screenshot and so on to stitch them into a whole page screenshot. 
We have to scroll the page via CSS to keep the state of the page intact. The default browser scroll would trigger scroll events and this could lead to side effects (dependent of the page).

**Comment by zinserjan** [comment]
Works for me now with the latest master. But I had to remove the following line in the index.html:

```html
 <div id="test-data">Test Data</div>
```
Can you test this with latest master?

**Comment by bennett000** [comment]
@zinserjan your current master (thanks to `npm link`) worked just fine for me and I actually left the Test Data div in place
