### ISSUE TITLE
Virtual scroll strangeness

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [zinserjan/wdio-screenshot#22]
So I've found some strange visual artifacts occur in one of my tests. I tracked the problem down to this virtual scroll execution [here](https://github.com/zinserjan/wdio-screenshot/blob/master/src/modules/makeAreaScreenshot.js#L38). I've found that specific line of code is not even necessary for my test case because it's trying to scroll from 0, 0 to 0, 0 (not doing anything). So I was wondering if it would be possible to only execute that virtual scroll when the scroll indexes are actually different? I'll add a pull request to show what I mean.

**Comment by zinserjan** [comment]
Can you show me an picture?

And scrolling vertically works with that fix (please test with chrome) ? This is just an issue for 0,0?

**Comment by Blackbaud-PatrickOFriel** [comment]
![wrong](https://cloud.githubusercontent.com/assets/11620552/18066484/9cd53dbc-6e06-11e6-8949-c527e877b0c3.png)
![right](https://cloud.githubusercontent.com/assets/11620552/18066486/9f3b6428-6e06-11e6-9223-4ce0682121c3.png)

The incorrect image is the first and the correct image is the second. I don't know if it's just an issue for 0, 0. But it seems like the error happens for me in this case when it attempts a virtual scroll that does not actually scroll anywhere. I'll run a test now to ensure that scrolling vertically on chrome works with my fix.

**Comment by Blackbaud-PatrickOFriel** [comment]
Scrolling vertically still works. I ran a test that took a screenshot of an element that was 5000px in height and it captured the entire thing

**Comment by zinserjan** [comment]
And does it also work for your test case? The Modal with a height of 5000px.

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, my fix works for my test case as well, the modal with a height of 5000px.

**Comment by zinserjan** [comment]
Sounds good. Can you provide me a minimal failing test case (html + css)? I would like to add integration tests for this to avoid regressions in future versions...

**Comment by Blackbaud-PatrickOFriel** [comment]
Yep, give me a day to come up with something that doesn't rely on my library code

**Comment by zinserjan** [comment]
That would be awesome!

**Comment by Blackbaud-PatrickOFriel** [comment]
Here's the minimal test case https://gist.github.com/Blackbaud-PatrickOFriel/a745661b1c4e1e7ca9066147a30fff8c. The footer disappears when using the `saveElementScreenshot`  method with the `body` selector, or when using the `saveDocumentScreenshot` method. My change fixes the problem for both situations. Thanks for taking a look @zinserjan

**Comment by zinserjan** [comment]
Thanks for your example. That helped a lot!

I found another solution that does not depend on removing virtual scroll for the first scroll position. It doesn't feel right to skip the virtual scroll for the first time. I would prefer a more consequent solution like removing virtual scroll completely.

Anyway, can you please test the changes on the latest master? Then I would like to close #23 without merging. Thanks for your invested time and your support to improve this!

**Comment by Blackbaud-PatrickOFriel** [comment]
Just grabbed it and tested it out, works perfectly!

**Comment by zinserjan** [comment]
Nice! Released as [0.2.1](https://github.com/zinserjan/wdio-screenshot/releases/tag/v0.2.1)
