### ISSUE TITLE
Add JSDoc annotation

### ISSUE THREAD

**Issue by monolithed** [zinserjan/wdio-screenshot#33]
It's needed for [autocompletion](http://webdriver.io/guide/usage/autocompletion.html).

```
/**
 * @alias browser.saveDocumentScreenshot
 * @param {string} fileName
 * @param {Object} options
 */
```

```
/**
 * @alias browser.saveElementScreenshot
 * @param {string} fileName
 * @param {Object} options
 */
```

```
/**
 * @alias browser.saveViewportScreenshot
 * @param {string} fileName
 * @param {Object} options
 */
```

Could you please add these annotations? 
I have not found a place where it can be added without refactoring. I mean:

```js
export default async function async(browser, fileName, options = {}) {}
...
```

**Comment by zinserjan** [comment]
Hmm, seems that we should refactor the commands to remove the browser parameter like [WebdriverIO commands](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/saveScreenshot.js).

Can you test this out with the following approach? This would also allow me to see if my last improvements were successful (complete test suite should run for PR's)

Files to change:
* [index.js](https://github.com/zinserjan/wdio-screenshot/blob/master/src/index.js)
* [saveDocumentScreenshot.js](https://github.com/zinserjan/wdio-screenshot/blob/master/src/commands/saveDocumentScreenshot.js)
* [saveElementScreenshot.js](https://github.com/zinserjan/wdio-screenshot/blob/master/src/commands/saveElementScreenshot.js)
* [saveViewportScreenshot.js](https://github.com/zinserjan/wdio-screenshot/blob/master/src/commands/saveViewportScreenshot.js)

```javascript
 // index.js
...
  // add commands to WebdriverIO instance
    this.browser.addCommand('saveDocumentScreenshot', saveDocumentScreenshot.bind(this.browser));
    this.browser.addCommand('saveElementScreenshot', saveElementScreenshot.bind(this.browser));
    this.browser.addCommand('saveViewportScreenshot', saveViewportScreenshot.bind(this.browser));
...
```

for all commands: remove parameter browser and declare const browser and assign this to it
```javascript
...
export default async function async(fileName, options = {}) {
  const browser = this;

...
```

**Comment by monolithed** [comment]
@zinserjan Look at my PR https://github.com/zinserjan/wdio-screenshot/pull/36

**Comment by zinserjan** [comment]
Awesome! Let's continue conversation on this in #36
