### ISSUE TITLE
new Release?

### ISSUE THREAD

**Issue by xcambar** [zinserjan/wdio-screenshot#50]
Now that Firefox does no longer support full document screenshot, and considering that the project can not point to a git hash in package.json (because of build), will you please consider releasing a new version of this package so the support for FF is maintained?

**Comment by zinserjan** [comment]
Yep, I'll try to do this after work.

**Comment by zinserjan** [comment]
Done as [0.4.0](https://github.com/zinserjan/wdio-screenshot/releases/tag/v0.4.0)

**Comment by xcambar** [comment]
:+1:
