### ISSUE TITLE
Still failing with mocha async

### ISSUE THREAD

**Issue by mparpaillon** [zinserjan/wdio-screenshot#58]
I'm trying to make it work with the mocha framework, but I can't get it to work.

I keep on having this error

```
Timeout of 10000ms exceeded. Try to reduce the run time or increase your timeout for test specs (http://webdriver.io/guide/testrunner/timeouts.html); if returning a Promise, ensure it resolves.
```

I've been trying to change "sync" property to true, add "asyncOnly" of "mochaOpts" to true too, and my test looks like that

```js
it("captures Account view", function() {
  browser.url("/account");

  return browser.saveElementScreenshot(`${outputPath}/AccountView.png`, ".Account-View");
});
```

Would love some help, thx :)

**Comment by zinserjan** [comment]
> change "sync" property to true, add "asyncOnly" of "mochaOpts" to true

You answered your own question already. Both options together makes no sense.

Closing as it has nothing to do with wdio-screenshot. 

PS: Have a look at https://github.com/zinserjan/webdriverio-example. If you don't want the async/await stuff, just set sync:true in wdio.conf and remove all async/await.

Also there is a gitter chat for webdriverio to ask questions like this: [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by mparpaillon** [comment]
I tried every combinations of those optios (but indeed this one was stupid). Anyway I managed to make it work by just making everything synchronous. wdio-screenshot uses async/await apparently and once transpiled doesn't seem to return a Promise. So I just set a ridiculously huge timeout and make it all synchronous. No more errors... Thanks for the lib
