### ISSUE TITLE
Using jimp instead of gm/GraphicsMagick

### ISSUE THREAD

**Issue by knownasilya** [zinserjan/wdio-screenshot#6]
Think it would be possible? https://github.com/oliver-moran/jimp

I think more people would use this plugin if they didn't have to install GraphicsMagick.

**Comment by zinserjan** [comment]
Nice find! 
Avoiding external dependencies makes definitely sense when there is a equivalent replacement.

I'll look into it.

**Comment by zinserjan** [comment]
Released as [0.2.0](https://github.com/zinserjan/wdio-screenshot/releases/tag/v0.2.0) (#10).

**Comment by knownasilya** [comment]
Woot!
