### ISSUE TITLE
browser.saveElementScreenshot() does not work

### ISSUE THREAD

**Issue by franciskim** [zinserjan/wdio-screenshot#60]
`browser.saveElementScreenshot([fileName], elementSelector) `does not seem to work for me. elementSelector was 'body'. It fails silently - I'll try provide more debug info... can someone confirm that this works/doesn't work on the latest version?

**Comment by klamping** [comment]
Can you post the test you're running? I was able to successfully run it just now.

**Comment by franciskim** [comment]
I'll write a small standalone script to see if I can replicate it.

**Comment by franciskim** [comment]
@klamping - works fine actually. Thanks for giving me a sanity check 👌
