### ISSUE TITLE
error with chromedriver 2.28.455517 mac os in cloud

### ISSUE THREAD

**Issue by maggiesavovska** [zinserjan/wdio-screenshot#77]
Error when trying to use wdio-screenshot. I believe that it results in the driver crashing because I get no more data back from the driver after the error occurs.

OS: Mac 10.12 (or any mac os) 
CHROME DRIVER: chromedriverVersion=2.28.455517
Chrome Browser version: any version
 
ERROR: ```"message: 'unknown error: unhandled inspector error: {"code":-32000,"message":"Unable to capture screenshot"```

- issue is only on mac
- Issue is only in cloud service (sauce labs and crossbrowsertesting.com are the ones I've tried)

On my local machine it works fine and I also have the same setup: 
OS: Mac 10.12 (or any mac os) 
CHROME DRIVER: chromedriverVersion=2.28.455517

I'm not sure how the "cloud" part comes in to play here. 

NOTE: I have not yet tried other versions of chromedriver because I myself don't have the ability to update these driver on the cloud service.

NOTE: webdriverio "saveScreenshot" command works fine in this scenario. The problem is specific to wdio-screenshot.

Logs:
https://gist.github.com/maggiesavovska/95a5e44fe065cfc1c3fcfa33293e580b

**Comment by zinserjan** [comment]
I have this issue also with saucelabs. That's why I stopped testing chrome on MacOS in #74.

But I have no idea what's wrong there. I can confirm that it works on my own Mac without any problems...

**Comment by maggiesavovska** [comment]
Ok. Do you think it is an issue with the temporary directory that it being created? Strangely enough in crossbrowsertesting.com ("chromedriverVersion":"2.29.461585) It will take 4 or 5 screenshots successfully before crashing. If you can at least give me a clue of what to try I will troubleshoot it. 

Thanks!

**Comment by zinserjan** [comment]
I don't think so. The capturing of the screenshot fails on the selenium side. 

Just found this: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1802&q=%22Unable%20to%20capture%20screenshot%22&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by zinserjan** [comment]
I close this, as this isn't a wdio-screenshot issue. Hopefully this gets fixed soon.
