### ISSUE TITLE
Stitched together-screenshots get horizontal line "artifacts" in Chrome 59

### ISSUE THREAD

**Issue by mansn** [zinserjan/wdio-screenshot#78]
This issue can be reproduced by running the wdio-screenshot tests in Chrome 59.0.3071.115 (x64). See the screenshot below:

Generated screenshot from Chrome 59 after running **npm run test:local**: (.tmp\desktop-responsive-document-1600)
![image](https://user-images.githubusercontent.com/4518977/27684733-80802438-5ccb-11e7-8a07-fa213393b4c7.png)

This might be a Chrome 59 issue?

**Comment by mansn** [comment]
This doesn't occur in Chrome 58 (verified by running on Chrome 58 on Browserstack).

**Comment by zinserjan** [comment]
Can you open an issue in the chrome issue tracker?

**Comment by mansn** [comment]
Sure. They probably want a good explanation on how the merging of screenshots is done, and it will take some time for me to explain that. 

I'm currently trying the "normal" browser.screenshot-functionality to see if I can reproduce the issue without wdio-screenshot.

**Comment by mansn** [comment]
I haven't gotten around to create the issue on the chrome issue tracker yet. 

Anyway, I just wanted to say that this doesn't occur in the current Chrome Beta (Version 60.0.3112.50 (x64)). So fingers crossed that it remains that way when it goes to the release channel.

**Comment by mansn** [comment]
I'm closing the issue, as it doesn't really seem to be a wdio-screenshot issue.

**Comment by zinserjan** [comment]
Cool, sounds good.

**Comment by mansn** [comment]
Chrome 60 is out on the stable channel now (since July 25), and I just want to confirm a second time that this issue is **gone** and not reproducible anymore!
